version: "3.8"
services:
  nr_node:
    build: 
      context: .
      target: nr_node
    networks:
      nr_networks:
  postgres:
    image: postgres:latest
    volumes: 
      - data_postgres:/var/lib/postgresql/data
    restart: always
    environment: 
      - POSTGRES_PASSWORD=password
    networks:
      nr_networks:
    ports:
      - "5432:5432" # postgres

networks:
  nr_networks:
    driver: bridge
volumes: 
  data_postgres: