version: "3.8"
services:
  nr_node:
    build: 
      context: .
      target: nr_node
    networks:
      nr_networks:
    depends_on:
      - postgres
    environment: 
      - NAME_RECOGNITION_SQL_DIALECT=postgresql
      - NAME_RECOGNITION_SQL_USER=postgres
      - NAME_RECOGNITION_SQL_PASSWORD=password
      - NAME_RECOGNITION_SQL_URL=namerecognition_postgres_1
      - NAME_RECOGNITION_SQL_PORT=5432
      - NAME_RECOGNITION_PORT=5000
      - NAME_RECOGNITION_DEBUG=true
      - NAME_RECOGNITION_QUERY_SCREEN=SELECT key_screen, value_screen FROM screening;
  postgres:
    build: 
      context: .
      target: nr_db
    volumes: 
      - data_postgres:/var/lib/postgresql/data
    restart: always
    environment: 
      - POSTGRES_PASSWORD=password
    networks:
      nr_networks:
    ports:
      - "5432:5432" # postgres

networks:
  nr_networks:
    driver: bridge
volumes: 
  data_postgres: