version: "3.8"
services:
  nr_node:
    build: 
      context: .
      target: nr_node
    networks:
      nr_networks:
    ports: 
      - "5000:5000"
  nr_balancer:
    container_name: nr_balancer
    build:
      context: .
      target: nr_balancer
    restart: always
    ports: 
      - "5001:5001"
    networks:
      nr_networks:
  nr_test:
    build: 
      context: .
      target: nr_test
    networks: 
      nr_networks:

networks:
  nr_networks:
    driver: bridge